"""add business tables

Revision ID: 0002_business_tables
Revises: 0001_initial
Create Date: 2026-09-23 20:08:16.178579
"""
from __future__ import annotations
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0002_business_tables'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_mappings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_system', sa.String(length=128), nullable=False),
    sa.Column('target_model_id', sa.String(length=64), nullable=False),
    sa.Column('mapping_type', sa.String(length=16), nullable=False),
    sa.Column('field_mapping', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_mappings_name'), 'data_mappings', ['name'], unique=False)
    op.create_index(op.f('ix_data_mappings_source_system'), 'data_mappings', ['source_system'], unique=False)
    op.create_index(op.f('ix_data_mappings_status'), 'data_mappings', ['status'], unique=False)
    op.create_index(op.f('ix_data_mappings_target_model_id'), 'data_mappings', ['target_model_id'], unique=False)
    op.create_table('master_data_models',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_data_models_domain'), 'master_data_models', ['domain'], unique=False)
    op.create_index(op.f('ix_master_data_models_name'), 'master_data_models', ['name'], unique=True)
    op.create_index(op.f('ix_master_data_models_status'), 'master_data_models', ['status'], unique=False)
    op.create_table('mdm_quality_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('rule_type', sa.String(length=16), nullable=False),
    sa.Column('expression', sa.String(length=512), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mdm_quality_rules_model_id'), 'mdm_quality_rules', ['model_id'], unique=False)
    op.create_index(op.f('ix_mdm_quality_rules_name'), 'mdm_quality_rules', ['name'], unique=False)
    op.create_index(op.f('ix_mdm_quality_rules_status'), 'mdm_quality_rules', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mdm_quality_rules_status'), table_name='mdm_quality_rules')
    op.drop_index(op.f('ix_mdm_quality_rules_name'), table_name='mdm_quality_rules')
    op.drop_index(op.f('ix_mdm_quality_rules_model_id'), table_name='mdm_quality_rules')
    op.drop_table('mdm_quality_rules')
    op.drop_index(op.f('ix_master_data_models_status'), table_name='master_data_models')
    op.drop_index(op.f('ix_master_data_models_name'), table_name='master_data_models')
    op.drop_index(op.f('ix_master_data_models_domain'), table_name='master_data_models')
    op.drop_table('master_data_models')
    op.drop_index(op.f('ix_data_mappings_target_model_id'), table_name='data_mappings')
    op.drop_index(op.f('ix_data_mappings_status'), table_name='data_mappings')
    op.drop_index(op.f('ix_data_mappings_source_system'), table_name='data_mappings')
    op.drop_index(op.f('ix_data_mappings_name'), table_name='data_mappings')
    op.drop_table('data_mappings')
    # ### end Alembic commands ###
